apiVersion: v1
kind: Secret
metadata:
    name: huginn-secret
    namespace: huginn
type: Opaque
stringData:
    APP_SECRET_TOKEN: ENC[AES256_GCM,data:wo8R8nfInnfF7P8KyVUSCrQeNyCTopiy5Sqk+U1kU7f2tbxne3Skhev5+dzMx9zpwgxKs9SpzEhuPtAHDam8k3MMATB+6tS2Y8oly8dZYoJhMkBN4COm2pkpJ0qdq9MM2aQCp+tupL103OCLU00x/zMA5lL8YsZiVpmW5pEugJM=,iv:ksKDdQzmcl1eFJMttInwBZHV91YZewOEJW+k3Cfwhs4=,tag:O9z6LlmAtuHYWeFPOBlwNg==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:cj8x7l39q3krCjXcYHTgyVTcUgyM+8FkUX6Lako8+B3z1R4lUNCATgn5WO2eSOKUjIVsDz4Vm4ANd8lTwzv+VyyqsgTdTc/lQioBys+2LbbvdjdEWqqG95fPEuWCNwbqMnttWc9fGt39rzr/Dmun41RRuenLb9FnJ1ISS10mi/E=,iv:r1FQJY1nAIiTQbxIH9IptvtXBwbMAzcwWSip0xLgs6g=,tag:2ZUcNbk3uREVx0sL7Ew6rg==,type:str]
    SEED_PASSWORD: ENC[AES256_GCM,data:fyTuChLIgV2bUGMF2+Q4470MIb8b11jsP5/I+NOGQAwoew==,iv:IoCwSTlX9UPyPVXjwkbR+tCbfQ2die4U+ujYPH+08RA=,tag:nJGPM4DWlxrfd1F4FUjoAQ==,type:str]
    INVITATION_CODE: ENC[AES256_GCM,data:oPYbi/Rmm4hlO8SpkRDF98DmajfEY2Cf8GA1,iv:+5UE8RvBTkrXTQswPVpGUaANZNsP7KXO4DueaykBTRE=,tag:AyiE3M1TMr1VO6uckP0LBg==,type:str]
    DOMAIN: ENC[AES256_GCM,data:trABpdINdaYe/rZxr/I3UZzyAUrucbvrtEE=,iv:+WSSRb4GXhnXRvZwhzGTXpsZbIhrmR0WFM0w5xVPnm4=,tag:Pr8KvrS8hzS/Ym/pu6pY2A==,type:str]
sops:
    lastmodified: "2026-09-16T20:41:47Z"
    mac: ENC[AES256_GCM,data:IarprqCg7BuI5AGkmVGrAmFNo3kYqr68mCvEbUr0xX7QEtan+KRkr4WJ1gIhoiaCV83KKfkjdO80esxkr/C17U+f4PbszYKwZ4la5TkBranC/ARnFzYS5zie6gSWbdDA3C2q80QgTlOdKu+GlRDkNy0OlaCm8b3CFlIBaAOniQ0=,iv:mlar/ugcKyu5AVa4OAMtvAO1j7NdWmnVr2vBIjmGdoU=,tag:8uv7wIeTMJUqqAndXgxCUQ==,type:str]
    pgp:
        - created_at: "2026-09-16T20:41:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1R72LzcpgpmARAAg2TMpPgfu3dLGnahHEMqPTFJZk7IQtJWHhmvMPzUB0Mf
            WU9ML8B+TnerNZ1OG3o4uU60JXW9YWt2qS7yczYA9U1cJkUmdv8u0vWrup405Asn
            ui9xnboAv4I0RSBs7lsdzsCpNWjWLWMgbT81AIdmGQTxiAAJ68MrUCYKY4JH3bZV
            N108HlRiapGJ5lgISl9B9SidYK+jhQL9/4zpJ1bCsd3gqRcDZMjQKDqPaeASSS9t
            QxFXdvowqAU/LKjIT2xhxzNOK8i3yEC6KrwAQdFPkQ1SnY5H+rrZwkPCgbDqIW5g
            6/vRNf2wt1yWtcUgWzGXaIR8JdXTc4NBLO3YCel+SuT55Wj/yaz48J6+/xKgTBD6
            uS+zB9r/ytbyNUh/AkkiyiGA8cEoHOYVtB6dmxsvv/kY8nF3uJaOheVuwcRTVP2I
            /sBFq2qw7kwtZQxtv/rMzSVa6IOzIYfp7szIIJvvn6Y7ixoFI2SfI/MiM6IYwCR/
            tHL4+LuKoIzGnJPKP9GHC4yn2VKrlQHyOVYbzYqsg16qnmxts1bKQbSjNPSGkO+9
            RhcefKhDMJNtdwiAJ7RR2GQQD4YFhr2SoUfGCXfq/729Ue1K91xVBoULIOXeBsB1
            b24w/uAbzLXX9aL1e/8tvTjgiO+Qv9PTXf/ZUuhCYSmh/jQN3RxhVYKBD+PUaXTS
            XgGxdns+/yR+0BHXeTiMMtdN5lrbJklj8EXOcGc9YruRWWqPvs5hrrHNpFEYn41P
            ZE0+Nh1n5R+8CTB3u09G2s9wyB/ZbcsUPiucP6m9x7ZdFsv9k8/XQ7fJj7iT+Ac=
            =GTxH
            -----END PGP MESSAGE-----
          fp: 08083A92DBB719D2E10998259B44720A645D6802
    encrypted_regex: ^(data|stringData|email|apiToken|host|hosts|tinyauth\.apps\.[a-zA-Z0-9_-]+\.config\.domain)$
    version: 3.12.2
