kind: Secret
apiVersion: v1
metadata:
    name: headlamp-admin
    namespace: kube-system
    annotations:
        kubernetes.io/service-account.name: headlamp-admin
type: kubernetes.io/service-account-token
sops:
    lastmodified: "2026-06-08T10:22:35Z"
    mac: ENC[AES256_GCM,data:XHTv7gkDZP468rQfdzqu7/P79fbKfXpT8Tmcd6hWG8wsfPi0a6hUyZb/RFX4pOxjAaoQRhCT95AdmLpFXx6t3UPGUNwVsO+e5DZPzm8pZIJV44VxG6jEpieEANhm4ae8+ppYE6sGb/9u5/J/zkOkr1umkAvviBYjrjs/EI1VzJ0=,iv:VYQY46FcpEBUiDYrSTxSLIAQ7yz/jcL9G6HrqEGPW9o=,tag:z4MU4sJHFDEjDt5QHoKTVw==,type:str]
    pgp:
        - created_at: "2026-06-08T10:22:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1R72LzcpgpmAQ//QE22bkHzaK2nvFyxIXawg14WxBQPDQ1ggCwn746yPXh2
            4w1UXDVt8kV7xBwRZn5EkX6oLDJ0dkPxAXvd1YsictPvP/a8c/9lpyBHD/P55iCT
            6iYm8FWJvdLvr2Ngxz1A0hHaNwyM+KV3zwUD/fql9vVSJrde01yCSkVj7Th2kWoW
            FKJZpRsW/jGbmUqymMtHVr/n1xSU20vufWzMk/ki4Was+BgvcR6J9Iwzg2a70TVW
            ZcE+TPy6IJkC6YhF5T9Gb6HI2cMgsGtN30gmDxNNFPx9wpKRuihyIB8HMdoCiclX
            BFAi/WxAZMKGo110TfH2EtZpm8HL7EIfHpb1kd5BFWPcwZqs3UJoHIDgxE+j4gg7
            8Cg6PbLOP9aLMe9cIIScLJxVIhCHgPrd+bXmgOs2jS48uIGNgOaSo+nLPKOkHBdH
            x2EYnB7WAfxdfaQSRjxr8T59adnCW3GJHgrYHSTohgtb7p5f4DDWkNRGXOhpyjxD
            wJ5FUG7CfWilkb/iemzkiBqfv88mdDihK316N6zd+X91sh4cRhCOF9+fhF0j/net
            JqNUxzmZCLKPb9HyqanYZgkGRCN0FrKhCr+dmhS4R0VYdqaCoETGaOnom/6tOzP9
            9dz907DyBj58x3iVBihxYwyIST03497SoQgPJjqViQV/RpHSyhIoKl3Ma36xcTPS
            XgGHSHpQwf92mOzDMTxft3NqFNdcjksXO8K/I9HSA63uY+ksVFacX3eXlRJqJqSM
            9TH3dp/Kbld8mjneQwz7uHTFJ6nu14b6Frm8yGrJBTCYnea+9FAXosVBma4Qq4Q=
            =koAU
            -----END PGP MESSAGE-----
          fp: 08083A92DBB719D2E10998259B44720A645D6802
    encrypted_regex: ^(data|stringData|email|apiToken|host|hosts)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc-secret
    namespace: kube-system
type: Opaque
stringData:
    HEADLAMP_CONFIG_OIDC_CLIENT_ID: ENC[AES256_GCM,data:ZJqjeChQBHRJEW/K58iTlvqNkdTChnlb/nZ5wQpmLxRkp3+t,iv:hLfEXzx0cVm69Gi9Gc7YhR1rPI/bp0pTYltvBFbbJQg=,tag:fGRynvl7TvE5ejBLXoWpGA==,type:str]
    HEADLAMP_CONFIG_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:MSSWOoa87WJVpVXnyLKArnbaXhFF9bSSq+v7NoD1GUD9q1Hs+ccixjGLptu0onE9drLuS/u4AIV6zRO/5NrVYg==,iv:XOycw1aqGG+XXfuaDDYDUNnVeL5esENIYacUyU3yG78=,tag:re7f+HWDTvKVZ2fcTRwIDw==,type:str]
    HEADLAMP_CONFIG_OIDC_IDP_ISSUER_URL: ENC[AES256_GCM,data:O06PNmxIurogX3M8msKDE8WzRg4QWDbIQoSHhrjJocixYhxJ,iv:ExXv3kGiRkPZaEhWUEL0nCgDTwAocwHXdFMgN6t1DgA=,tag:pALoSeRBNIQKejgI1HTfww==,type:str]
    HEADLAMP_CONFIG_OIDC_SCOPES: ENC[AES256_GCM,data:1nFTcjRNIUwtLUmmpg==,iv:Wo8XvLbrA1we+P4MDLgWvQ02xI1GH9q02c9orXKvjWI=,tag:YHtg4H19ImXS0ycRqLj4BQ==,type:str]
sops:
    lastmodified: "2026-06-08T10:22:35Z"
    mac: ENC[AES256_GCM,data:XHTv7gkDZP468rQfdzqu7/P79fbKfXpT8Tmcd6hWG8wsfPi0a6hUyZb/RFX4pOxjAaoQRhCT95AdmLpFXx6t3UPGUNwVsO+e5DZPzm8pZIJV44VxG6jEpieEANhm4ae8+ppYE6sGb/9u5/J/zkOkr1umkAvviBYjrjs/EI1VzJ0=,iv:VYQY46FcpEBUiDYrSTxSLIAQ7yz/jcL9G6HrqEGPW9o=,tag:z4MU4sJHFDEjDt5QHoKTVw==,type:str]
    pgp:
        - created_at: "2026-06-08T10:22:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1R72LzcpgpmAQ//QE22bkHzaK2nvFyxIXawg14WxBQPDQ1ggCwn746yPXh2
            4w1UXDVt8kV7xBwRZn5EkX6oLDJ0dkPxAXvd1YsictPvP/a8c/9lpyBHD/P55iCT
            6iYm8FWJvdLvr2Ngxz1A0hHaNwyM+KV3zwUD/fql9vVSJrde01yCSkVj7Th2kWoW
            FKJZpRsW/jGbmUqymMtHVr/n1xSU20vufWzMk/ki4Was+BgvcR6J9Iwzg2a70TVW
            ZcE+TPy6IJkC6YhF5T9Gb6HI2cMgsGtN30gmDxNNFPx9wpKRuihyIB8HMdoCiclX
            BFAi/WxAZMKGo110TfH2EtZpm8HL7EIfHpb1kd5BFWPcwZqs3UJoHIDgxE+j4gg7
            8Cg6PbLOP9aLMe9cIIScLJxVIhCHgPrd+bXmgOs2jS48uIGNgOaSo+nLPKOkHBdH
            x2EYnB7WAfxdfaQSRjxr8T59adnCW3GJHgrYHSTohgtb7p5f4DDWkNRGXOhpyjxD
            wJ5FUG7CfWilkb/iemzkiBqfv88mdDihK316N6zd+X91sh4cRhCOF9+fhF0j/net
            JqNUxzmZCLKPb9HyqanYZgkGRCN0FrKhCr+dmhS4R0VYdqaCoETGaOnom/6tOzP9
            9dz907DyBj58x3iVBihxYwyIST03497SoQgPJjqViQV/RpHSyhIoKl3Ma36xcTPS
            XgGHSHpQwf92mOzDMTxft3NqFNdcjksXO8K/I9HSA63uY+ksVFacX3eXlRJqJqSM
            9TH3dp/Kbld8mjneQwz7uHTFJ6nu14b6Frm8yGrJBTCYnea+9FAXosVBma4Qq4Q=
            =koAU
            -----END PGP MESSAGE-----
          fp: 08083A92DBB719D2E10998259B44720A645D6802
    encrypted_regex: ^(data|stringData|email|apiToken|host|hosts)$
    version: 3.12.2
