kind: Secret
apiVersion: v1
metadata:
    name: headlamp-admin
    namespace: kube-system
    annotations:
        kubernetes.io/service-account.name: headlamp-admin
type: kubernetes.io/service-account-token
sops:
    lastmodified: "2026-04-21T12:26:34Z"
    mac: ENC[AES256_GCM,data:PoYlf8VyieX/dbWVAo4nLBf/a6xWLWO6RrZ8WdKw5oY34TYrm/sCmisNNloybKe7lu34vGmTwYk8dav1fr4EPdqqLI6WwPz00a+Dm9eJAmqIspU+Tq0Bnkiq8ZQuoC9qUIg44nNkbVZw6WYYxN5ZkFmrbOriSVUp2BmUyYcUB88=,iv:nJqGtl0jeARRV5whNQm9RLOWeQL0fFdpNViYNzGHjs4=,tag:0I9ruDb2P0FR67SLSxkRYw==,type:str]
    pgp:
        - created_at: "2026-04-21T12:26:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1R72LzcpgpmAQ/9EzRPTyteJy0CEUGsP7FDRpiqx7OJkkEyfyNykv37sF7H
            2se+rI3EY2MFYoD7linXfZ8MfBXw41wfTMmTAJkr+ZFHCWVIXGX5HyC4KVUO2G5m
            9/PfdH+Fh/2RQJQRFpxn6fckcYymmdXy0fA4QIFuIZQr7pMKK4nEasrYXUcTHmQp
            E4Cojap/rphr05N5XMFzV9b1wkzatETWf1njOYbMn2YLkxV+7kfAoswJPxS18v9r
            qlMJ1wQZKlLWlBHbm8JbSFYsUuaVLXKWF0cOMaAd5nPBGiY9ZKR5Dwf0u80nsef6
            fH0B25D7yy1S2WfSXh7hVF5ZlKM46RnOZ4DB+Z3POnntjyJQlVGzHz3Hq5ECqLQF
            qn4rnGKYfHtsgJ4gK5kcu94YXdTay5EdvYpX5Z0g9nmDR/xHfKvRl6DyV/QTpMKe
            8nxnBZCKkSpRslThQMQ4nab6wt52bPf1H7SVWy1xqg0V4VdjVE8Gibh/hF1NKRAb
            0SyXiTR63b0eYO5vlnuNq6NVA9s0LrMTzRbeepu1T16XzQvpoPqaw74qVCUIXFtE
            lTYgPT7rQmJobZrIEeiXqMfEbOemm70xArR2H4EmLhHwfnJaFDQDE9j+HMobsYLY
            m2iDtXroP12IU7j2VJa6i4HQHkpxTXKnazMrgppRSZ7eMtzOkWSzHMB6bjlGKkfS
            XAGLLyVjI6ifLEMuZ4ne5uj6hN19ccUKyER08eLsSAE0C0VkS6a8QVa6qWNiWFS2
            pW2Iq69sqFiNHYUEIoha1qDq6q5c9bfHrsA9zLvLpVxPTwLCPSbmubOkOCdW
            =insv
            -----END PGP MESSAGE-----
          fp: 08083A92DBB719D2E10998259B44720A645D6802
    encrypted_regex: ^(data|stringData|email|apiToken|host|hosts)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: headlamp-encrypted-env
    namespace: kube-system
type: Opaque
stringData:
    HEADLAMP_CONFIG_OIDC_CLIENT_ID: ENC[AES256_GCM,data:p28KyWNu/Bhi1mPz2LbGW+OfcMJAeaPQ93kRazmSyn4j7GlH,iv:Eav5sRUOsF28ntz4pG0oNWFvm1f7+UhRXipF7g2W9Hw=,tag:cikqojzsHq1Fykungf5HWg==,type:str]
    HEADLAMP_CONFIG_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:2X54CMcYK2SCyDYexc/ZVPDf0MpJ4M64BGl99YvL9U8FbSRmwDZIGidx6Q7hmO5Yl3aJK8QO3ex5s70iDGtE+Q==,iv:wc5LUDzfGHuJJi0TYduRt435l9cbJ5nxg4k2jbQfp9A=,tag:FxU/5YQ78HElVg5YSpm1DQ==,type:str]
    HEADLAMP_CONFIG_OIDC_IDP_ISSUER_URL: ENC[AES256_GCM,data:Ava3/tywJG7vv1H5635irqBOHoZBAjxlTVZXsTz4Aj0rc6gt,iv:1r6F64er5Iv2FGOK8cwNsVz86w+kltHaLMr59hdjaJg=,tag:c7vC4hM+QCywaVuZGGauQA==,type:str]
sops:
    lastmodified: "2026-04-21T12:26:34Z"
    mac: ENC[AES256_GCM,data:PoYlf8VyieX/dbWVAo4nLBf/a6xWLWO6RrZ8WdKw5oY34TYrm/sCmisNNloybKe7lu34vGmTwYk8dav1fr4EPdqqLI6WwPz00a+Dm9eJAmqIspU+Tq0Bnkiq8ZQuoC9qUIg44nNkbVZw6WYYxN5ZkFmrbOriSVUp2BmUyYcUB88=,iv:nJqGtl0jeARRV5whNQm9RLOWeQL0fFdpNViYNzGHjs4=,tag:0I9ruDb2P0FR67SLSxkRYw==,type:str]
    pgp:
        - created_at: "2026-04-21T12:26:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1R72LzcpgpmAQ/9EzRPTyteJy0CEUGsP7FDRpiqx7OJkkEyfyNykv37sF7H
            2se+rI3EY2MFYoD7linXfZ8MfBXw41wfTMmTAJkr+ZFHCWVIXGX5HyC4KVUO2G5m
            9/PfdH+Fh/2RQJQRFpxn6fckcYymmdXy0fA4QIFuIZQr7pMKK4nEasrYXUcTHmQp
            E4Cojap/rphr05N5XMFzV9b1wkzatETWf1njOYbMn2YLkxV+7kfAoswJPxS18v9r
            qlMJ1wQZKlLWlBHbm8JbSFYsUuaVLXKWF0cOMaAd5nPBGiY9ZKR5Dwf0u80nsef6
            fH0B25D7yy1S2WfSXh7hVF5ZlKM46RnOZ4DB+Z3POnntjyJQlVGzHz3Hq5ECqLQF
            qn4rnGKYfHtsgJ4gK5kcu94YXdTay5EdvYpX5Z0g9nmDR/xHfKvRl6DyV/QTpMKe
            8nxnBZCKkSpRslThQMQ4nab6wt52bPf1H7SVWy1xqg0V4VdjVE8Gibh/hF1NKRAb
            0SyXiTR63b0eYO5vlnuNq6NVA9s0LrMTzRbeepu1T16XzQvpoPqaw74qVCUIXFtE
            lTYgPT7rQmJobZrIEeiXqMfEbOemm70xArR2H4EmLhHwfnJaFDQDE9j+HMobsYLY
            m2iDtXroP12IU7j2VJa6i4HQHkpxTXKnazMrgppRSZ7eMtzOkWSzHMB6bjlGKkfS
            XAGLLyVjI6ifLEMuZ4ne5uj6hN19ccUKyER08eLsSAE0C0VkS6a8QVa6qWNiWFS2
            pW2Iq69sqFiNHYUEIoha1qDq6q5c9bfHrsA9zLvLpVxPTwLCPSbmubOkOCdW
            =insv
            -----END PGP MESSAGE-----
          fp: 08083A92DBB719D2E10998259B44720A645D6802
    encrypted_regex: ^(data|stringData|email|apiToken|host|hosts)$
    version: 3.12.2
