kind: Secret
apiVersion: v1
metadata:
    name: headlamp-admin
    namespace: kube-system
    annotations:
        kubernetes.io/service-account.name: headlamp-admin
type: kubernetes.io/service-account-token
sops:
    lastmodified: "2026-05-17T08:48:34Z"
    mac: ENC[AES256_GCM,data:maVMem/+MJhC5Ppeo0xyUdZV+qXJPIU240M5VmFwUPWuL97gOQpFC0JcOt6i2F+GpnC+TZdzc8oyChitBPIzZMbDfPIlupoIy9RqveEpNE0spG55RNbFHSCgTgzRK3j/V/ICZg7sWC7vmMmkQdI1m9C/gmP3ZiOGV1GdFHrshj8=,iv:rXd300nKZKRL3oFb78upJHKHwOkFdJIvwt7sjmqfeAY=,tag:fhs895oo3xspkhoIC9EZLQ==,type:str]
    pgp:
        - created_at: "2026-05-17T08:48:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1R72LzcpgpmARAAjpiZT9BzdRkU3MPGApQ400mPW2gwd1rNHKpgJ33nFHpE
            XdGTxi7WXzr6MG7TzXmJXdJCRyEb8fclWrmUND37DN2LuKdvZZPqc65Wo4huBQTr
            GrXtft8OKJ4zy9fvq8GovBh35JPxeid00i3jYikCEIIGo6mUSsBbCGdDB1ETTb1V
            pBCb0SYbWs5TwZo5E1+pTaD0BduAov0TFQ49DgD8pmAu5yyEdr3hRbLqYu5cXXqj
            OWBCKSwmOZF9JFNTw/TZo89e4nrEV2IpbEMK6WowLr3r0kq5IIKsN7kgkOmNx+pi
            3Qv8+P02yylkvYfNx+z0kf6pWBVwoaroZgjqbehGkvkSOe5/ZWLUkqOW31NrCA9q
            KbEAOyLxJ3Eox9QMjl3XpqPyIztHpbBOoTbPIBv7svcPfBRt6FQxzFXteaWfHUWv
            mHn6Bn74uJJZQead4cXiYWIZeiQoET86xsBQARx3U7cRvf/TVFk8Q0pyxTHs3wNu
            Q/H+NoW6U8BGVO1iWPwGgKmoz0iBDgiW2u91abfQyXi6TdLIRMThEJMpE2zjek+z
            gKmJc/EF4uI4ejYB9SkViHtxEyKWQLSwCu/96ZK2ghTNhFSe1My7359JN6GTuRxL
            eoMqvEXdC+zMWZDWmZX3rs1QikIS5SEshuqyeTNk87zgWTeCfPgx6sMIm5JpEFrS
            XAFSHXPjfdlm5kcb0z6ZbY3KX4yiacdpsMgvf90NkRlPRGaIXJwFQjgQU6Be6WlT
            JABx/+RsTjirovNRYA6C9qEA32nR+nS/UTlASSj6XC11lTBcxHwMMtfzEMDP
            =TS1F
            -----END PGP MESSAGE-----
          fp: 08083A92DBB719D2E10998259B44720A645D6802
    encrypted_regex: ^(data|stringData|email|apiToken|host|hosts)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc-secret
    namespace: kube-system
type: Opaque
stringData:
    HEADLAMP_CONFIG_OIDC_CLIENT_ID: ENC[AES256_GCM,data:semd8h20yw0NhMdl82cZkjRugiwwj78VfdL/hR7PdcIWsCaN,iv:pjpBUPI1sOUDzIsc8Tr0DazN8SQLCPYs8faE7+tFG6k=,tag:B6ABhKitrhadK+lNq1k2TA==,type:str]
    HEADLAMP_CONFIG_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:2SWKsFWB5LgFwEGdAF/aIJpsRss3fsmsEtqTh/n8U/T9bl+znL3yx8fgaQZR+ACOW9hTIo4UR5eATC/ufGtviA==,iv:CbSpMWs0IYPlJmpnalJedBuHLLYHPtqtbBEc+XGZTs4=,tag:Jr3Kp81tR6Uhb76wBZc9WQ==,type:str]
    HEADLAMP_CONFIG_OIDC_IDP_ISSUER_URL: ENC[AES256_GCM,data:NJIqIuIYQNgUDqjJjeVMTLJPCmQ0lTg9AN7V9o+t0Mac4Pmj,iv:amsJFMaUF7o301Jz/T3TcvEopu+yQHDRE8aK1tZLQXU=,tag:bYkPbpRrwlw0PZSD+5X8yA==,type:str]
    HEADLAMP_CONFIG_OIDC_SCOPES: ENC[AES256_GCM,data:0qZo7djHQDvhwTiVPl/QYR4LpRo=,iv:qSGJ6E+Va6XCbOv4PR3UWndBKJxu2S9/HDz052vfhtQ=,tag:IbajgBeOBDU/YYFX6AmlVA==,type:str]
sops:
    lastmodified: "2026-05-17T08:48:34Z"
    mac: ENC[AES256_GCM,data:maVMem/+MJhC5Ppeo0xyUdZV+qXJPIU240M5VmFwUPWuL97gOQpFC0JcOt6i2F+GpnC+TZdzc8oyChitBPIzZMbDfPIlupoIy9RqveEpNE0spG55RNbFHSCgTgzRK3j/V/ICZg7sWC7vmMmkQdI1m9C/gmP3ZiOGV1GdFHrshj8=,iv:rXd300nKZKRL3oFb78upJHKHwOkFdJIvwt7sjmqfeAY=,tag:fhs895oo3xspkhoIC9EZLQ==,type:str]
    pgp:
        - created_at: "2026-05-17T08:48:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1R72LzcpgpmARAAjpiZT9BzdRkU3MPGApQ400mPW2gwd1rNHKpgJ33nFHpE
            XdGTxi7WXzr6MG7TzXmJXdJCRyEb8fclWrmUND37DN2LuKdvZZPqc65Wo4huBQTr
            GrXtft8OKJ4zy9fvq8GovBh35JPxeid00i3jYikCEIIGo6mUSsBbCGdDB1ETTb1V
            pBCb0SYbWs5TwZo5E1+pTaD0BduAov0TFQ49DgD8pmAu5yyEdr3hRbLqYu5cXXqj
            OWBCKSwmOZF9JFNTw/TZo89e4nrEV2IpbEMK6WowLr3r0kq5IIKsN7kgkOmNx+pi
            3Qv8+P02yylkvYfNx+z0kf6pWBVwoaroZgjqbehGkvkSOe5/ZWLUkqOW31NrCA9q
            KbEAOyLxJ3Eox9QMjl3XpqPyIztHpbBOoTbPIBv7svcPfBRt6FQxzFXteaWfHUWv
            mHn6Bn74uJJZQead4cXiYWIZeiQoET86xsBQARx3U7cRvf/TVFk8Q0pyxTHs3wNu
            Q/H+NoW6U8BGVO1iWPwGgKmoz0iBDgiW2u91abfQyXi6TdLIRMThEJMpE2zjek+z
            gKmJc/EF4uI4ejYB9SkViHtxEyKWQLSwCu/96ZK2ghTNhFSe1My7359JN6GTuRxL
            eoMqvEXdC+zMWZDWmZX3rs1QikIS5SEshuqyeTNk87zgWTeCfPgx6sMIm5JpEFrS
            XAFSHXPjfdlm5kcb0z6ZbY3KX4yiacdpsMgvf90NkRlPRGaIXJwFQjgQU6Be6WlT
            JABx/+RsTjirovNRYA6C9qEA32nR+nS/UTlASSj6XC11lTBcxHwMMtfzEMDP
            =TS1F
            -----END PGP MESSAGE-----
          fp: 08083A92DBB719D2E10998259B44720A645D6802
    encrypted_regex: ^(data|stringData|email|apiToken|host|hosts)$
    version: 3.12.2
