apiVersion: v1
kind: Secret
metadata:
    name: tinyauth-secret
    namespace: tinyauth
type: Opaque
stringData:
    TINYAUTH_APPURL: ENC[AES256_GCM,data:LgApWs/cHUhahRjG6YLqPKZup+dsQuABw2TJkRxtbkJGBliP,iv:QlQND3u1w/O0JQHfPxKQm8ahrplvrv9zxh3LiM9cunY=,tag:Zcr0q5jedD8L9w0SFS478Q==,type:str]
    TINYAUTH_AUTH_USERS: ENC[AES256_GCM,data:z58Wysau0WDfyWOU6wVVzRnHE0GXow6XSzXom2zSh4lUkvpOneT1JCXRJANAlaIZUq7jX/I3YcnWPcrLEYkuB32KZupIWPY+U9aKW1w4u/6b2JOZHyhMTNGpxa5aZhVdn51P4BVCTRftHuKVMpX2LMx/5DC4nu+5StVTqlD1LDne0w5dXYL3P+D2mvLIzOJY89l3BLPZct5uqcHce/CsP1PgyuFUreMCI1KYXFwIBUMsoJ9iDAXu0Qg5jgn66VsCKQWaUAc65pMOFOl5iRDKRfcp,iv:+hhISiW5LD2KKJC0MjHcPU9+I3brvvurGFPCildbGEo=,tag:0cf86bOhCqJY8OJJVPzGIQ==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTID: ENC[AES256_GCM,data:g6yOYzKQDwrmhVQm0ftWbE++dQY=,iv:qwzB3rLApjEj7ugNw0ITqPnBMpWPoTnblQPdSkUTJ70=,tag:T7CIwv4zko9+h3+65lCe5g==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTSECRET: ENC[AES256_GCM,data:fHu/Wh5jkClRvVkvniK8VcI1jVq9+bCcFwOLI6TX2fJHc1vPHF0NwQ==,iv:H3keHR4n5JpE2OblTl4kNvxstv+EZQEYQWHiZ9WjqCw=,tag:9JziEGHR6HsvKbsEbXbLiA==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTID: ENC[AES256_GCM,data:hGiDt2N9REr7hG80IffrV3gc3VzX+l34KHJjJCEIR1iEQen9SY5+FmgLY7E/oAythIDQm6qhlLdymcjYSc+2j0v62iR39pqT,iv:sESdFPDdZqhWTiMr4HVerqT5vCnUIeRnnkBevi8Hk9Y=,tag:KOvtdLx8GzFwDkjRlRVYSw==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTSECRET: ENC[AES256_GCM,data:oD03XtIiU39xLYNbP/WKaubFQ4bG+RTfLTo6X3nDV0up400=,iv:CRHmRQCmrkaULOuA2nX3gudzwNkcgnTi11P8kqBScKA=,tag:+ApsIXkQTMpGeAz95KyI6Q==,type:str]
    TINYAUTH_OAUTH_WHITELIST: ENC[AES256_GCM,data:wMibQ5EhoQ4hYOUJwJ9/+wZfTG4Fdw==,iv:CEamygs1xtMPFyWugI54IRXkTADwOwxDfqHrLVVCkNA=,tag:5BCRdUaMnlS4Q18BXw3Ueg==,type:str]
    TINYAUTH_OIDC_CLIENTS_ZEROBYTE_CLIENTID: ENC[AES256_GCM,data:udakdbwe/WNqWLLteXVn7eDHaJiegxu0SSJtGUf+sIhetuhM,iv:rcfmVTr+1/D1rmX0lsuj8yZJFGVExBJoVKoVnhNu4Jw=,tag:3tawmtCwIEiusW+fQpBkgg==,type:str]
    TINYAUTH_OIDC_CLIENTS_ZEROBYTE_CLIENTSECRET: ENC[AES256_GCM,data:yQWjuZQGQVAq5S/JrPMh4wYQIrjhU07a/WEZ5GqwoZu5AVBAqP3j9KiRRGjhrwNGzqq0PSwclXkaTOvblj+CxQ==,iv:HuNqg5Si6DNpD7vqpshriTPpRZlrvVsTgJsaowfM6qk=,tag:hG8X5v9wvgxG5Giw9HfeRw==,type:str]
    TINYAUTH_OIDC_CLIENTS_ZEROBYTE_TRUSTEDREDIRECTURIS: ENC[AES256_GCM,data:HoRC89yzp3YUZPr/gbtriJR2+mZ4+5pPIMlfgX5pRb+cm3e0yXl8v7wM/LoQU8bZbIOGE6KEDqUTV8NDnChTPguseg==,iv:HcNObNgGqWEkX8TMD8yjaHa+qMm/y/VyzNWM/YNX1JQ=,tag:rmzZHLiSROQT7I4qT1ok6A==,type:str]
    TINYAUTH_OIDC_CLIENTS_ZEROBYTE_NAME: ENC[AES256_GCM,data:icQR0i2EpHQ=,iv:/DmdwgttvttxCjKKnRbWVmWaOZEk8ToOog/G9N1mPJ8=,tag:mJjo+JpnZ0ti1TvHLhGg7A==,type:str]
    TINYAUTH_OIDC_CLIENTS_BESZEL_CLIENTID: ENC[AES256_GCM,data:90ZmQefcuFnQFAhwIhWNNauPf/TX7S4dieN41VTOfMzmcaLu,iv:fDT4KtGsswbMOYkfvx6rhl/DQiXEils02NJQAeLXdKM=,tag:4aNkWlazi5ZSnNRT2n+m8g==,type:str]
    TINYAUTH_OIDC_CLIENTS_BESZEL_CLIENTSECRET: ENC[AES256_GCM,data:8bwUDMFU/rEB7bLs5lRXtGuwicfTe0XlgdltE2Ui54DPtlMAdk8oATfRSDNyF2af9X+bpcmNcyvQfHdd7f6+jw==,iv:Q1uHpTdO9FlTqeXYZCf1slyDSGa7A1jxBTNq2B03uCY=,tag:GpHDc3cYm5l1XJbTwv+COg==,type:str]
    TINYAUTH_OIDC_CLIENTS_BESZEL_TRUSTEDREDIRECTURIS: ENC[AES256_GCM,data:8Gu6AJgghNz5DGyYwNafC6UQMbBw3BPbXxGhxFmw5cQd0cohd1VEjKrBRwVMu8vEbS4Q6dv9,iv:sQ5riYM/9U16q5YyyWAeBihxlVLmi1cYqF55yi5JyPM=,tag:jYx4Za0lVB4S5QStrS4POg==,type:str]
    TINYAUTH_OIDC_CLIENTS_BESZEL_NAME: ENC[AES256_GCM,data:1n2r/tB+,iv:jOIGNUwMgDHVS5cWqA7+m/zEOpR7ZL/e1IAz14h7H3Q=,tag:OufKbAhjZ/0Zu/PeplVa/A==,type:str]
    TINYAUTH_OIDC_CLIENTS_HEADLAMP_CLIENTID: ENC[AES256_GCM,data:9bPsfmXQ4wPNbZDYKNhv90oAxjsegfOW3vW3d5kI+T+dfT5/,iv:e4FiZrpwgx9brZPha46O7alIpYjPDvHCXoZ2KEyJa8o=,tag:z5XMWOMsqZ8eQA0A4DeuCw==,type:str]
    TINYAUTH_OIDC_CLIENTS_HEADLAMP_CLIENTSECRET: ENC[AES256_GCM,data:mJtVSPSwqiiGTUCwby6mAqERXuk8lfNR/zzADwX5EVK0MOiOHUAXIPRkWCbRTPrnjGein1j4ZJRM+3UIkx/atQ==,iv:pEBmf7egVe395mOeuAgjO6EAaGSLJoDSzTgTmPhcnqE=,tag:FBGx5y3zG/Qlj21sm52/lQ==,type:str]
    TINYAUTH_OIDC_CLIENTS_HEADLAMP_NAME: ENC[AES256_GCM,data:sV1SCELp0kg=,iv:Oo9o7KG5RG67Xmuhz4iAyP5jtHd5s21t6R5DNU+I47E=,tag:Da8ltMZYOfw5BF0JN0JUrA==,type:str]
    TINYAUTH_OIDC_CLIENTS_HEADLAMP_TRUSTEDREDIRECTURIS: ENC[AES256_GCM,data:7inr9VwSFnQfWd4zQ548tAOPiYdxnkmxJkB9Rx/kh92n6neDCpHG7w663j0a4xEgAWk=,iv:RIoToG7tH5jBsG68q7d0fQSXsiIJrUetFAntS1r9IXg=,tag:0k40cEx98psHgD88xHXahA==,type:str]
sops:
    lastmodified: "2026-05-17T08:48:22Z"
    mac: ENC[AES256_GCM,data:eu0OU7+oQfFF013sY/EkLFJKwXB2oiM4uYCJzpmf53JEpBgJgncU2wJ0SJFc96R/GXjzGJkBkC12ElEtKAIzis9fJvoX3jB2+Bl4ED4wA88qEjQGUWhdnjTDSs9zSVI2dBjjPfXBVEy018zxCvvGswZJHrg5v1v7ogmoPu4R+IM=,iv:O5bl5fRLjBgB2it0hi1oPjQK9jfuVx4y5Sbj0kVdSaM=,tag:f9NwAyBufN/4P413BBrEdQ==,type:str]
    pgp:
        - created_at: "2026-05-17T08:48:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1R72LzcpgpmAQ/9HhYfFllUOuEfNKaaVs7jc8C5Fk6E7s+5rFCvDmQqo/Nx
            xPaF8hT8ZBcALLsku8IIIO+yEWU0cfme5teMe0b0++51agRar3ArBhZeSY4Swqtd
            Yqjv4XF/lvSZnU673OM5ZojRoW3vPrdZOUg+0N9+CehtqHJ955DFUeCvMHFUoSd2
            uAaHC79OAIrs1av5201V+5lfDwCJ5Wogc16cNv4xsy+kro2eiR+vmWeTT9CrPZTo
            YoyWMG1C2Ub3sCrFc3R4u5QbnOCa7lmCvL+jMQYGBTyT0GjTYPFjqjjdOj0ZkZ9A
            nhmpH7/iEwGxFddKPS9TtoYavixyJ3hpeBLG1zSIQ3go556QUF4Eim73ZvvLbBIt
            bX1LbI5SP1RrWw8VcH/3HFmykCADFgi0CWyqNxpajav0azL+bwnKhRbqU3P+u015
            BbteWq02UvHXyLmd+4ZabC2MTgCPYOHtpjkDNlM63HWuCaBYlp9fb9TVbIqdGna/
            Egw7DfKLVgVRUPmX4dDVWfy6IazP7T1xPyLXrywVg02VRaGx8Pn4/qIcQzSQStiI
            acu2wO86AmrqxRgICYdBeJGJpTjsuvhSbZIozGRk9sOepfZh1b/AKeWv3W+C09Lb
            gudErsNqts+3yf1/D5F88XWkf4mbcY47O+10GDHdBchbB8QleFIf9F0uo1vVYtLS
            XgFUQByo6fCRlsNnC9eE7fF5rtezy3FI7jO6osSDZvPNpm9XiNNB5N4fjCakZH8d
            x9u9I9f7ufHaz75raZJ/wXpbFazoYZse1mO74kjGbUTI0Ge1QzG8o92MPh79h2s=
            =uAQp
            -----END PGP MESSAGE-----
          fp: 08083A92DBB719D2E10998259B44720A645D6802
    encrypted_regex: ^(data|stringData|email|apiToken|host|hosts)$
    version: 3.12.2
