apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    annotations:
        cert-manager.io/cluster-issuer: cloudflare-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        traefik.ingress.kubernetes.io/router.middlewares: infrastructure-redirect-https@kubernetescrd
        traefik.ingress.kubernetes.io/service.serversscheme: https
        traefik.ingress.kubernetes.io/service.serverstransport: warpgate-transport@kubernetescrd
    name: warpgate-ingress
    namespace: warpgate
spec:
    rules:
        - host: ENC[AES256_GCM,data:DBt3lpgHU7er/bIa8P1wjlhwfrtMMzrrilhoBA==,iv:CdSg/qWBpDGrCha3765ZnB+J3yUAOPENn2og6M3IuxM=,tag:OpGyr0MH9rmMD6RuT3Ztjw==,type:str]
          http:
            paths:
                - pathType: Prefix
                  path: /
                  backend:
                    service:
                        name: warpgate-svc-cip
                        port:
                            number: 8888
    tls:
        - hosts:
            - ENC[AES256_GCM,data:W+YX5ou3xKKpn1cvfp+146+PXnfB/7hc6Oivtg==,iv:qX+3iPllv2iOzV4JRAfL3u0B56AoybxNUvol+VCgQdQ=,tag:i2nzrhRJ2CxMUL8jNKlFZw==,type:str]
          secretName: warpgate-cert
sops:
    lastmodified: "2026-06-04T16:03:17Z"
    mac: ENC[AES256_GCM,data:+UI4TWWZybM1wbKV4+K7iGk58h+AtZgpsE9lU+JJVddWqHo9lvYUjdfZfSncx5M3XGbBFNdLg+Tw//uPrzsZtmLSVMIsr0N2wD+s6XOh+G+5CMF1h36GneWOs90kUYv9YBfzEu0v/KL1+GepfxnqqjH8F2F5FHa+e1T1p7MHWuM=,iv:R2R444ofW6Uid3FLGPNC9sHz1mhUp2fAkOSkfdvJYXE=,tag:cinAIEKoqYoMgNKX5fBOlw==,type:str]
    pgp:
        - created_at: "2026-06-04T16:03:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1R72LzcpgpmAQ//fKjw9g50BDHk/Yu+8uOKWlB8uvSDUWjdwuIwsPCIqV5K
            k2vm3TrByAu81KGmJVapw6dyLpdaFXjQtljYiZZpAi73Y84yjIRBArNfeaZ/oW+i
            kI0uYJCJ7pjrZPyDFUb0guTXtNRv7cGa/0BzBkifdfhAqfHKrXM+7Fdx2H4cAtiK
            6OUYZsaJLULABIgnF4Zylon+4XwviZdLSjxEZ6CSE4MaGxqxisXiTlD+SON4Hlyg
            2+zhNEPlsuYRraV1vKa+/2HIHbsa77r6VGJpd0Ro9l4xQLi7g5JdXS23R2xDhxvE
            fhmUaRGUe4ntX6XfzxhqQskUKmV46IY+Em5Qo7ABIpDmBhq24uHyOpVe4GSLrxT0
            AEocmTgfVj7X2Astxrbs8O1+YVWC2BKohFlmhUeCR9B3TRokZqlUgHloBFuvmrYL
            YjdDZpVuDoaufm4H7X39zFZpF+jZF5sgc1m/Hhr/x1zwWsPpU+ScyzW6QYNKZOEk
            +Kn6Q5WazgG+lSELfm4fHPUgxhsW/hVVjYP0dVjVQ1zs3gP+d7ir8i/2CruoISu3
            +22M1I0NoSeOZfCAbMv7VOfouWmwj9tL9d6SezRIODGbcDteRmoigsGCF0JEoqlo
            +eSVF/7OquHS0I4bgYPLlEzfdKg2omSZrDZH66hJ34azr0iCxeAdd4gX97ObQQDS
            XgGjTo3lB+Q0yCTC/YYgEIbqh0osS8KgmJccBl+9KSVsHZfiLY6Kto3JcNTC4JTS
            HqjCC4BH0jqWxBV769CQAxKwOruqrvsKRBPbFBZ+0PkzKSp5h7PKF29lfqD0wh4=
            =s37g
            -----END PGP MESSAGE-----
          fp: 08083A92DBB719D2E10998259B44720A645D6802
    encrypted_regex: ^(data|stringData|email|apiToken|host|hosts)$
    version: 3.12.2
