apiVersion: v1
kind: Secret
metadata:
    name: warpgate-secret
    namespace: warpgate
type: Opaque
stringData:
    WARPGATE_ADMIN_PASSWORD: ENC[AES256_GCM,data:WNm5+iRe5RNCU0CpbO4fLdZJMLvHK/cPxC4C,iv:aR52CPauSwLY0ixrpyDvRPq63OJxnwvCKtScpUsyRyI=,tag:hBtTeetwodfFVRkDeuGF+Q==,type:str]
sops:
    lastmodified: "2026-06-04T15:53:00Z"
    mac: ENC[AES256_GCM,data:Kl334s6ZSQTKGzGjnN9j9dttG39UKe1zvPRpSEiEbWgL3LL1mu5d/BAPO5y51MxbKwcpYBojllzDr5IkSu3utKDiuuA0g4gf9/2eX9S51W3DkeUO5NmeslUf2dG96NT76W5q+yCw2i2mdhovzA1tIUbNu+BNp3F1v4hJGkVsQaM=,iv:4pAh+T6u/higHkB5luOGm9dqYgnGT9GSgLuQpd4+vNM=,tag:5CDks47qGqpkEQojjG5hBw==,type:str]
    pgp:
        - created_at: "2026-06-04T15:53:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1R72LzcpgpmARAAhZdF9F0Pusaw9zbRo/zvc/P23Z7dkIb5cThqShqaDeI6
            VGx8HAtl4wM6iP5lOWSyOvP3MP3Sh2pbv7vy1ASHIvxX5GHH/+qRTqeDGeudzQHf
            Mjb1JGppt/1TE95CQ72aqTCkfwq/tXqEEk/A1EmCTj86EkTtTQZnWPwwbwgO0cY0
            GyUJaPCWQlWZAmR5toNOiNwH2P7WiisxgWmLk9oXCilwu/BHvkg+bzS9hCoF56Qo
            8fCxnBPDaSxMGjx1YyP0a8WtoRWjtAgLiILfNDc0R6hHCBoMvL7u5eEqd3rdzMLw
            B1lDXbrN5NltwMJnqdcSyf8jmTLR+R5N5XDjiv4CtTlZUAvtlzJKWpo2NUWwFdzu
            r2Zyx/u6WPXMSIW5jmber3xt4RphYR7f/6Ug1HAZF3EE/eX6nytpckZGROTdsikA
            sdrfEPA8qXwvzdYsqo7GGg94YbXMFgKxcYlVeY4TNVC1bqop8vVkRprjbIj9yJJE
            4QfpMmveuQlXvYITXRRi4LgiCmGuKrYZn6SeRQ1IpVOFDF2TpkK5cjNlXVzyPLcX
            PxRDobzZMLPudL7HykMqIHgWEz+bv24OSXmoED0psh4xDzev8E7GTjDOFJ/MV8La
            gQH+W+ueWNkr0vMfOLh/Qt5p2TGhBvpj4gvYULAvL2kYdSALEtlZ3JSCrp/4HRbS
            XgEtQ9SK2o1vdyhyRCxehWSVfmcWyBLuqo88ZBlHUbH/Zhpsp/4KcwMN7Lr/pWpZ
            VyXoJ68Cng3Fvjzz55dzFp5WFsNZ8S7ax/CFYa2xnYi9XLN5GHfpeNXhLrDvnRs=
            =h1eh
            -----END PGP MESSAGE-----
          fp: 08083A92DBB719D2E10998259B44720A645D6802
    encrypted_regex: ^(data|stringData|email|apiToken|host|hosts)$
    version: 3.12.2
