apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tinyauth-ingress
subjects:
  - kind: ServiceAccount
    name: tinyauth-sa
    namespace: tinyauth
roleRef:
  kind: ClusterRole
  name: tinyauth-ingress
  apiGroup: rbac.authorization.k8s.io
