apiVersion: v1
kind: Secret
metadata:
    name: obsidian-livesync-secret
    namespace: obsidian-livesync
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:RE+hI5A=,iv:X650kahtZTgr4dEybOp1CSniW8n5hmw5dKlEfUWF8tc=,tag:giVOixoLiHqp2I2Lbe/m5Q==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:qLRQ1oXAPD0XWHDBmyzACpXUoZicvk3JZ3dXAXKLJpPCtXo=,iv:+XbMZsBZb/ej1ysPUjufxVFXXQST+0YGGBSJX4KKWgk=,tag:mwkmris+ZeNxp7kQgCBdQQ==,type:str]
sops:
    lastmodified: "2026-04-21T13:38:36Z"
    mac: ENC[AES256_GCM,data:KLwTqtnyWozS0GhINpirXWC5E24jx8ONrYz++Wr9pldpkDOTlysj6GMHh/ZMrolODqPnSGy4kQyKxTFVyv5K0LydwOR1X2/x4498KxnG47VzSQE89hkHs3+xC93EUXG7umAczsux+ul215nFFi6g633EQp2nrVeIRwNwXnWcS/M=,iv:TxP+UNEyEszDYi1YId6obdyErzhlzhLsq8JQXiariws=,tag:yGp9oiXuUP1myFwU/ThJIw==,type:str]
    pgp:
        - created_at: "2026-04-21T13:38:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1R72LzcpgpmARAAm2lNHalAEXd23SyLWmSrKRou3YP5648mg1DN/3nSwfCL
            /hz4HM6op7F2dqZyu2osL8Yzx49ev9oLWU1e5ifPQGdqkCc2N7ZOD7Ek5sfZ/0hk
            1FW/ZCfD1fWBV+lR8U6atNBeU2FjIIGjE9wKifhCdZX0Qqs3v08G93AQSRU1RChE
            1UhjvGEGDt1ArUztndo0ZTR3RSxC4UQihL8Dxz0xobJPypFY6hgEtHe9tk/13KvP
            e6reC8Khf1+TmjpquXTa1jDG3Dek1i0NoXsvns00N9BACIUhoGtTitxsFWmDoX13
            2lR4zZfbodQ6GSpvDGkesC5jfNd8W1yvPNvOdx4JM3o1poqyiM/J2OusuOPrrYzn
            MP+FG31i2IkjeC41aDLzjQpiPfD55WZECftzRRtFsV7CijmYCjo88G+c+7891MV8
            5S46d/JtDey7YMCJSSuHH7Uqg2a2zOAWdb1HUjL6Qyr8Rn4wmy6V+sBGvbsGXaup
            Ba/Of+C1etyzeCOr+qv5ewrEpr1cb7dcbJ0Wvsbv6+6i0h1R1r2++kx24xfCc4Bu
            MX5BpS+ZGpsKQj/f67hOb9ZpQunxVa8AZ2uc787m/Ef5ejQbUr7WPAc38ckvHoQs
            wGH78pjHKqVwQN9bclc8zfFcjA0HhqeA5znglxoyGeiJ+ahqQyeSOpbOIo0noI7S
            XgHzwK3dDHUFHaMG37NMbPXsfTq2GKneyiNT4r7SderQlYgtuNqqSwF6UOCKvHDb
            Of3QlpOuSOKFRv5ZCkWsu0f9/igr8w6ROJrtp9rznHqpCpSX5xWaYtGR1J2Rsfs=
            =Poq9
            -----END PGP MESSAGE-----
          fp: 08083A92DBB719D2E10998259B44720A645D6802
    encrypted_regex: ^(data|stringData|email|apiToken|host|hosts)$
    version: 3.12.2
