apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      spec:
        externalTrafficPolicy: Local

    entryPoints:
      web:
        address: ':80'
        forwardedHeaders:
          trustedIPs:
            - 10.42.0.0/24
      websecure:
        address: ':443'
        forwardedHeaders:
          trustedIPs:
            - 10.42.0.0/24
