apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    annotations:
        cert-manager.io/cluster-issuer: cloudflare-issuer
        tinyauth.apps.ta-domain.config.domain: ENC[AES256_GCM,data:l5NkbQzksJpgiWyZcP5T4sRYd8tpXhaCN2ZQjn0=,iv:XY+6Lnwhm3bfWen4fJqmk54LHgKOKEIRCH0U72PoDr4=,tag:7GUiZ6eLTZ0z7C6YD5qslw==,type:str]
        tinyauth.apps.ta-domain.path.allow: /foo
        tinyauth.apps.ta-name.path.allow: /foo
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        traefik.ingress.kubernetes.io/router.middlewares: infra-redirect-https@kubernetescrd,infra-tinyauth@kubernetescrd
    name: whoami-ingress
    namespace: whoami
spec:
    rules:
        - host: ENC[AES256_GCM,data:fXBLywinAWoshI/wuzjYlffiQcbN3EZXAzFBIcw=,iv:mFNSoqhe89vpjE6KQpM3lqa+PNoIWUHWM3ptRznV4b8=,tag:pbfXnk8e/GHt0lCGC8Zqrg==,type:str]
          http:
            paths:
                - pathType: Prefix
                  path: /
                  backend:
                    service:
                        name: whoami-svc-cip
                        port:
                            number: 80
        - host: ENC[AES256_GCM,data:lLDrS/4elSqwc+eei1YmG6N4+YNaYLTQmQNh,iv:uQFxLv+CAEkMw4JQQ2zH8LQtsV3G4z3+DVIdJkrd22Q=,tag:trW6uhvPhnUHSBaavEJrsg==,type:str]
          http:
            paths:
                - pathType: Prefix
                  path: /
                  backend:
                    service:
                        name: whoami-svc-cip
                        port:
                            number: 80
    tls:
        - hosts:
            - ENC[AES256_GCM,data:IWoeLd8cNCzTehJYoiq0zi2u5hGgBf5I3WZn8WI=,iv:JhY/VE1ItNqcT7LRUNKzIR5ysP9AcUThkTYdY2/N2qA=,tag:+zMOq89/EynoSCoDdaWxQg==,type:str]
            - ENC[AES256_GCM,data:9URGl3c+iZoA/VyLT8j8Hdp4TW6Wq3QX6ugy,iv:xL/AFLMfJG08PSau4iiJdxWlc7a117jM/FEbuNofqHQ=,tag:21g0/rUCukmro9j3D8lgIg==,type:str]
          secretName: whoami-cert
sops:
    lastmodified: "2026-07-20T13:59:13Z"
    mac: ENC[AES256_GCM,data:0iuhFJWWPy5BSNh4qJjRDMyUWMCd28zoMmKJ+YwzMhQhHQXS/+BUGuNHRXqB8U7vPuHtaGWHFvTns+U2pRqe2SjXO4/QfKupP9Bo0u7L60kKwu5I8jAyhPg6BRuQKQqms74ahLOKvitZvFIeYY0BvnKafvR3Ml0as2TUrkqEfOY=,iv:gaMeXsAy6PRfka4c1Te+9gxjMEN2MGYJHCoMea4XafI=,tag:2fQkViYZ0mpQmoIvGXXAcA==,type:str]
    pgp:
        - created_at: "2026-07-20T13:59:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1R72LzcpgpmAQ/+Ji51qkJp4e4bJhTmcoGksnINsnpSQYIzpeEt0FfjBC7n
            wgZxJd1E2hNdJ85PTZSCVVkfCMFiWA2JEg0MndUi1oGJ+8F9wsTISfLVdPskg4a7
            eYX+v1g0wm3JLB4K/hMKm+tGZZ6Rt+mLs4TSgRZaIp43XCIUpwQnCFv8mwlLOaSE
            Rxfz+yU75cJ5ecsVcs1TBdPnNq5Sdq3hKNAHZI3Y6VqNTMkDikBi205NMxE8RbEC
            B9qAd2mSN+Cuxg8nX32qlcfn63ccblEY360qs+n0GD0mmH7VOHRyAygsjE5BP8ga
            +NrHmu80EknxAJJrrEC9tJwhrA+BivF0uxmTqBdEiYKceENW2SfMwQpdrYkwoO+i
            PXKsQ7E1YflB4FIh5ys92yaFFKm1nYjtbE875hdng7UB56QqjyFdGxm05CmhqDuo
            PqqYYZZbPvDp9HUip72NrHZDQi9HhJAy6/Xowgrpli+XCqod6ouoiOvoe6K1qGJw
            8ltgiROScq2eF30yDCAm3pv0m+fcckxLXk8uQA/rRL+F/vhLcEuV+aGVzss7+5g3
            hhBibgfclMcc8P6tAJwgCV2pFhOjqk9RsGqrWZy8YZejZtBhZ9KTXl1hBYHv3Ho1
            CEZTEtcLmkQTA21EHhmUeySANKuo6BqLV2oRlXE/mY3/UOTW8GOJAd2t0iKIvKjS
            XAF2jmL6S9X4LwGlSSSepa+pqBcuEB5q3X9NHC4VPd4eqyqXGHWaoA8bPyB14gmD
            Vcsq+nTUb+Qyz4/1BZXdqcnPDqV2J+LPbH4tn0TC3lqcCZiNVarJ9Mh0mNrK
            =BNCA
            -----END PGP MESSAGE-----
          fp: 08083A92DBB719D2E10998259B44720A645D6802
    encrypted_regex: ^(data|stringData|email|apiToken|host|hosts|tinyauth\.apps\.[a-zA-Z0-9_-]+\.config\.domain)$
    version: 3.12.2
