apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    annotations:
        cert-manager.io/cluster-issuer: cloudflare-issuer
        tinyauth.apps.whoami.config.domain: ENC[AES256_GCM,data:eIqmLghVvG4XI2xggfQysXrl1V2GBVNvbyQ=,iv:Hn+CAktijalsX6k4Tv/d17RvRc7qgzVfKgZqy2VrBro=,tag:ajjjtSpE8yVWT1TSrDAISA==,type:str]
        tinyauth.apps.whoami.path.allow: /foo
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        traefik.ingress.kubernetes.io/router.middlewares: infra-redirect-https@kubernetescrd,infra-tinyauth@kubernetescrd
    name: whoami-ingress
    namespace: whoami
spec:
    rules:
        - host: ENC[AES256_GCM,data:WkZYVwT66h93QcOipbGWmCs8Hfev5ANLtz8=,iv:btKGD69W0eGEgFUKReM3tQTkFUOelkkcQ6AGh3PZN8Y=,tag:c+qHNovsNvdA1FEOVy7dNA==,type:str]
          http:
            paths:
                - pathType: Prefix
                  path: /
                  backend:
                    service:
                        name: whoami-svc-cip
                        port:
                            number: 80
    tls:
        - hosts:
            - ENC[AES256_GCM,data:Ea+4EqEVgALV3Lz72Ssw4+pMuOk3kmoHvUI=,iv:QHBzadHgPa2az5xo4Y+gRzWrsjiZC0giLGJE2nBcQ8Y=,tag:GofJRaueR6J97OGyz6qrfQ==,type:str]
          secretName: whoami-cert
sops:
    lastmodified: "2026-07-19T21:55:07Z"
    mac: ENC[AES256_GCM,data:XdAWNPiJPFVEIo3ISibVMKC0+edD3EJ0jg8ZonmZpa7d2yMwCx3yF+jvuFYIScOdxnnKtVd1K7rQ2sWF8CKNWRZItYaBXGQEQaPHshA9s75jb2FbGJVQahMN6QQIMfk/gYJxlPHR2HyRRDwaGLCDqP3hH0ByRwsbdz5FWyMkGMg=,iv:ZFzi108lNvdjZU2aDDrqXAhF3PwUNYRBLLCdlCg2xws=,tag:hY74wgXq2EDlXiPTCf+Gzw==,type:str]
    pgp:
        - created_at: "2026-07-19T21:55:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1R72LzcpgpmAQ//dCeksI4Ma8pdiIAHTUWy+UDP0zd6d0hD95/s0Wg9Mp5m
            m26Xw8jgskRkAyr5H82U2CRMkUckJGealACUCe5cOXROWCMuYE5/YUXN/mBvrURb
            oAmyYlK6ktuBRFIKZ9LvOba9Nj0bseb41x6GKUdU9JK6Jpx4NB2TXtgJYnQY2X9Q
            ubARLOY+xJRDPXn8bvIEkbm2o/b3Cru59d8QXECETH6isl6WZO6406gC74P0g1yu
            sceVjqcccJ5xWpaTsTP/KbBVVi52FSSEBoI+fQy7mMV1PMidVo94Gflop+/RdDOO
            tn+k1b6OeShQxv2+E+cIrCfjCVzTILPYYPi5mdZE7N2LgPzEJrAOwWL9mFCJzBJ8
            AkVkUyjHTK1UOEmoVj75q13BKIgIgSkteia9a32Nh7Js9yNqm6A+SD+uHI8j5s5y
            uzG4nVj+J6+BKLGtEGLMppBpBvQ1M1odheeZF3FmqgpnW7ydLnTkWRNbo2xaTz6W
            JSd9mFlwc/fDntQ/gkQJfiSJyItuOaklgwNtccWkCGS2TjuHWDE8i4Xyamdu4OVf
            OB9oRcyLfFfEqkd7HgnalEJqXROzbOPQn+a/tI7eA11D2Y4dG8YkAxRDl6cPUQyH
            aHi1v9JKHvXmHaEuLnb7Kw9Ihk1MZebA+nlsTPbxlQSPHmW2Ok+Q3hgNykeI0irS
            XgETerzKTFvU6kxa759SsrHVcv/4Q+i7Xz/bsU7ppRMALXvw5EJHbBv4cNAnJAyq
            cC/ReXuNEZqMPprnoVKxFGRj9lFKUDSQRk2JKxA8CBspMItHdX8hzKlmAbFG5X4=
            =SxHD
            -----END PGP MESSAGE-----
          fp: 08083A92DBB719D2E10998259B44720A645D6802
    encrypted_regex: ^(data|stringData|email|apiToken|host|hosts|tinyauth\.apps\.[a-zA-Z0-9_-]+\.config\.domain)$
    version: 3.12.2
