apiVersion: v1
kind: Secret
metadata:
    name: whoami-secret
    namespace: whoami
type: Opaque
stringData:
    message: ENC[AES256_GCM,data:/kfH78jPNt+pRL4=,iv:6a9W/irlWKYfwDXdDoDhbRCd6CsSxTyjNZaDsRZSMZs=,tag:AirsZApc7AgECEhx59yD6w==,type:str]
sops:
    lastmodified: "2026-04-20T13:21:57Z"
    mac: ENC[AES256_GCM,data:1ZqXl3Rqo3yUk5C+Be39XTb7YMYRx30ckWXleiyAWqkKs8DpWkar9ojQOb4IlUt2UVPEJrj7g2qCdr9vgW7/evPoEqpFCY4/g/joR3BlEJWK9JLglKUHdwoKfdlqC0Vxw11SAGpzbsGsFnCqrMsYmncrS0+tZ0dCQrksIml4byE=,iv:REQkDatolL0JlwiGTMjVW1pnfj54K1Jf/affUCnJNNQ=,tag:PB1CWOlTt25JiXWfGsdkdw==,type:str]
    pgp:
        - created_at: "2026-04-20T13:21:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1R72LzcpgpmAQ//ZFWsnKASpq7rgowRQvf78U3MpWgvUeAKwW1yYdDBVtMw
            ApUpXntL+8/O/JSp6vv/nXZzvf96t1MMaWvlDNn5NxlqOJr/zoPgW8LcRmcleBLQ
            a1mKO/njxSK+VIqfqQSOGh2uUEDWVwIkkaTn7UAJOzx55Vop1caPEvDpGtEa3713
            AzwxQSDtLbLRjszN7hbqPjzK6x8PwimzLBZd1fs/llHisrGzXMV8Hlof4LIEmT5i
            y6mWgp9RFObtLxIeKXTa+4FWtQNpoxK7IHmJDECu/iOYcWRgifoBv78Kt9Oag2OY
            UAQQH5LURDs4SGZn+EXMLF8xXz0q0G/X84wIGtGj/f1y61+XHWWqV2S950hMeIgk
            nVqx8ty4V9BqG9Nnr/hnXP+9rro0fF23OJ6Tr4lMuYdPHL6kNrpE5kJABUze6Iqh
            UClQWy3GXMf0mQ6zY/m+AtBIwjH/0WemK9OPBM7rEFv+oaPEmU5dXKmh0iMWHnx9
            AtgVWi/5v7J/CDu0h1Ua70RpjgyGTEkWDPCdJIB3og/D1lz8ml8N4ITTXReTIK0R
            pVv+lh5gXxuTPyEN1C8HSV7pT4fHEUMzqA0oVpyrMbblKx3znLyWq2XLXDOhbpc7
            HrCEZuvtnSv/mIKpSmeJQ4+YpurgJPbJTHjkjRS7P+AZ5QkXa93oHTaT0NF7DMzS
            XAGECPCu86rUR8daqqoS8nx6DhiFtz2p+S/TtqFkRa/GHwZgLpBSrhBc8Nx/P5Qi
            6rxec/2w7hwVohq7O8j7bkCdO8b8D9X7Jcp6MJa5Qfo06h1pL3EoIqlYbvCv
            =6jMM
            -----END PGP MESSAGE-----
          fp: 08083A92DBB719D2E10998259B44720A645D6802
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
