apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    annotations:
        cert-manager.io/cluster-issuer: cloudflare-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        traefik.ingress.kubernetes.io/router.middlewares: infrastructure-redirect-https@kubernetescrd
    name: your-spotify-ingress
    namespace: your-spotify
spec:
    rules:
        - host: ENC[AES256_GCM,data:P9pGxRrbUkWwoLyFbe9EuYRTlNnYTf2vO4QgXHeuvik=,iv:tEcc0z3eWng04K1P/jfKdRM3Ylb9jEAshXArlqQV5DQ=,tag:Tek8ptL2mHv9aszDOKcJiA==,type:str]
          http:
            paths:
                - pathType: Prefix
                  path: /api
                  backend:
                    service:
                        name: your-spotify-backend-svc-cip
                        port:
                            number: 8080
                - pathType: Prefix
                  path: /
                  backend:
                    service:
                        name: your-spotify-frontend-svc-cip
                        port:
                            number: 3000
    tls:
        - hosts:
            - ENC[AES256_GCM,data:xDvrMWnN5YtSwuaTwiwRVJMms0Twn0tJlASdwwCQJI8=,iv:TrQ3KLLR3GzGb8FbBKb9myHXKC2E5ip9Z2w5SmCNcWM=,tag:c1Z1p5tO7gibPXnwp/tgvw==,type:str]
          secretName: your-spotify-cert
sops:
    lastmodified: "2026-04-23T19:05:04Z"
    mac: ENC[AES256_GCM,data:8UwsauxC+ERNaApFck7pETW4KNQrpv3VK87Ejl3YzHp6yvGf2V7354dhasbGBWs0s1ffBuo6fXcwMRCiGFdcJophCy9yvMwPCDGk3Q/sel7x3fLQMO6+QFgoqHXDTHUkMv2DqolphFkO0+DTW7loXphZRz3gMVCa4qxATDUJqSg=,iv:d3tTk449cF8NS6sUMYXc8bA6r5YY5Pb6nv675nFONTg=,tag:CRouah/WTBKR4XJ5gGKZyw==,type:str]
    pgp:
        - created_at: "2026-04-23T19:05:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1R72LzcpgpmAQ/9E39hU44ZxVHPiRpjA+YnzKNvoSKv73PoqQXVwoC+FWqa
            VriDM+PImstvsPc13Oml4d8sk6h8/6bU5XfiUL5eduhJYDnNMSx1eDzuBRkVvUjP
            HLMDA2711CnNnKNb6NtQLTBi8sZpZveRjVj5nRT4I5PL2oMHUU0kh9v4nMkb3kzu
            mMCY+jT2lK+v5TYGFVUqa0DiQdTAwWz1CAX2E9jCsx5K1dNc3BBz2fVAg5WuAldk
            zCWvNc1R/MezKiFvS4MYDF0rYcl7NvXnwbqfEThKw7JN/6A4mDGdDbNGEw20RrSB
            9HM0DjzWTaVmKaX3VgUhzyPostQtxrI0KqMSzwfqFufFFtW7TLPBuKidbwtpPcGF
            Ji2bNM3HKAIQjrKACYr42P5VoMvj3fqa/1NE+MtwTZGXgfvz8CquT7qx9tLm15Re
            BX7liMA7nqrxxslARfBNrgnbA3gAGL6Bkx7JFnNuyaVBeXsaLpv7Yn5yY0P/I8y3
            TlMrCEwkswW2+pGlxKKDLYHcJebf3UWOWiiGChmsXg6xiv91aEwmpInHeTUR5orA
            Rl4O3LAZPDdRajco11tCEU0icicEKccQMQUCG2X07Fic3MVx8z3Q1wRwfDxpY2yU
            tKgv9xhD5rnhpRhY90OrEj70rjyuH8uRxW4o1EvvBUruAt2ZlQJO3Ht3iTcm2dXS
            XgEH9WkxpogtIvaY5ypGEz5bXQjlyEJ2R7NHD6kBMDDG/03o+KjMEMjHL7cYWy+I
            XXOLpOqEyy66U2WPIgCCdILs/QI6GfHnSqLLlZgZVtAbAydZYD+4FJJWHqynpDs=
            =f8G/
            -----END PGP MESSAGE-----
          fp: 08083A92DBB719D2E10998259B44720A645D6802
    encrypted_regex: ^(data|stringData|email|apiToken|host|hosts)$
    version: 3.12.2
