apiVersion: v1
kind: Secret
metadata:
    name: your-spotify-env
    namespace: your-spotify
type: Opaque
stringData:
    API_ENDPOINT: ENC[AES256_GCM,data:bFiEpEbbaubWWXe/QiU5C9mRFwCMl/FhLPEdfJj9psE6cPbhR60TRo+GUK1A5MJw,iv:wMOzc+lExCUupvGxpmwRNkqLxVfLJnui6DnyuAvjdR4=,tag:/H3YLqRbtLZBWzFzae3RaA==,type:str]
    CLIENT_ENDPOINT: ENC[AES256_GCM,data:U72Z96Ay8J2+s0ipvOb9Q9DrkSi9U2jeuN9L8QIu9OidJUiMEAnpLg==,iv:fiWqRoKGSafCKguJr7xN6xIJwSWn2Pex7zXrteV51/k=,tag:IL7G5gEpAb5FKOMV4ZyeyQ==,type:str]
    SPOTIFY_PUBLIC: ENC[AES256_GCM,data:OVmbA3otpZECIMDXFQQNOYi87+yY5J7D6NtYLR1YCI4=,iv:CyImHa26lY+jDA/fwapax/U0kro6E9sBA9gQCclvzO0=,tag:PDOMfIYSV/R132svwRyWRw==,type:str]
    SPOTIFY_SECRET: ENC[AES256_GCM,data:xlJhjuioYkCbngoYM1EVlMxc2aANpALN/ONxxDNHsEU=,iv:qQfaPTrs1pWFdETFNoidz4hGVn0CzOiN7jQ49PN205w=,tag:pxOVx1aEy+OzrVv0n+ML6g==,type:str]
    MONGO_ENDPOINT: ENC[AES256_GCM,data:ucAiiEjKF2UIZOcT0NYdNBFp9niI+OXVYB7+5eqLuFA1iBsoj2P4sLjJiPSmPAB2O2TIFjHoRg==,iv:IkMTUNHnphERmWwtswqJtYaFpFl0lcv/dNGAtBzxxpk=,tag:2POB7r3t881NbHfp1m4MCg==,type:str]
sops:
    lastmodified: "2026-04-23T19:05:12Z"
    mac: ENC[AES256_GCM,data:xCEFJj2n83riyEqqFsJelPKnj6oE6JcyELjSS14KhQQSfJo7mgDjderBPlRTscK5ApppTvrerbWkgPAwnQ1Lb2b/er72SL6YcdXHkPKY+6SXN11Qz+iByvSQO5KCxUDn1HWjmuet1hbbibhrOE20btPfmt7lKa0XQ1YOIVaxAlQ=,iv:ASZEGQflY6dMfdG958vpCjauuYdS++zUxmD4y/QWi/k=,tag:kyywSgrRcDDaxUYkRYzobQ==,type:str]
    pgp:
        - created_at: "2026-04-23T19:05:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1R72LzcpgpmARAAkXhFFiN1IRYKIQSR1Q4vv+mAB4W8lhKxeByWkJM0Rura
            3wHR1yD9dsXihcNRBG0nYwvF6liYtzkL4ZyF9aROkndYIYv4T3clFucF+x40Bx1H
            M+p0j+0l35rCW+uB2YBolEmeK8xyqMejHjLmY9ibo46LcWmvJT0mCQbp0R8wAtjU
            3jsKGIZarp01flOyDRwGg+LdjiqrNA8ppX+aplh4hnAiTJGBZZsRKNHSo6RfxnWa
            tfQZyZr+SWDMmOZkNu0cbuuqiawe8dyi+D+wW5Hq6gT9wmp07fNojJGxHdNLnVzt
            h3Gr78V8OnNduJqhie+SwOGUpnrFtTo0vtuQqiWL1NSoq1s1U4QssOIvxt+wO5cu
            k4rlsS04jqN1YM1kHfwHL7387K/5TuUUGoEJ57X1ktdhkOoNHdkwhrnGUCpc65Vc
            xSiaPIfZlWUtGnGETd3IPlA5e0fk22Luol5cIP2sY6NHoFFVObaZrZfI6K7dOuig
            N8kmFzye7NJAA7/iXWYnIGqu9qKcumM+6nxZRnlv34YlwQqD+bX6wWSJ85or8ESz
            Dgh9Z91XZueIHkHmFmOvy5JM0jt3eXJyDOUW0BcHI1D6RkNCekKjfxe53KgOoOFm
            YliAgH6C/zofzOA4OEHxZn8KJyxwXtJwrDCKA/ysBJe8DuU3UXeD3WoW5WntSYfS
            XAHK00s2arX/q1a5Ljnh1OHDniXm1tjSxqGX+JcTqO4AEYMLJgg0lx05HE6jWzny
            1rANZyEgPLpNYx1FHFMXQjz/UmTPPvl4P6GgLxiugSSOtL9sS66iy09ATIS3
            =FLy0
            -----END PGP MESSAGE-----
          fp: 08083A92DBB719D2E10998259B44720A645D6802
    encrypted_regex: ^(data|stringData|email|apiToken|host|hosts)$
    version: 3.12.2
