apiVersion: v1
kind: Secret
metadata:
    name: beszel-agent-secret
    namespace: beszel-agent
type: Opaque
stringData:
    ssh-key: ENC[AES256_GCM,data:AtPetY3NICZhMA+Bw2g+wj3+P15Bo3Yb80gprGoI1UL3Gv90WcdcZ9+iz5LCrX3O/MIWWSwl2iJCVMlGnSWHDqJpxSbEAHVyf7I5sTcNP90=,iv:KfnDMsN/n2aQLUCyZKeLifsBEBIQLG19sicaZhQNYpo=,tag:b5zvR4vP2omg23HFgxXgCw==,type:str]
sops:
    lastmodified: "2026-04-20T16:39:26Z"
    mac: ENC[AES256_GCM,data:ClYC2g/I1jtPcuk7RJ2nyeeeisHB5bIWpqYLLSf0Kq/CghlNrQ/+kFAG9KxiXHzmFmAgvI9E3HcxajVsu6w5PZh+A4j4wL4Cy5Ku8qAPt0NAqjJ4K0pM1Y+dKcDLpCePZkR8LGE35YgxlRYym75F97w1garTMD4z2fgJd7Ep78I=,iv:WrYVda6eoLHbkUf2hHl+HdhHkZA3KgefyF/ZYNAR5Ag=,tag:GIRGn+iisb/TTkSxN79r1w==,type:str]
    pgp:
        - created_at: "2026-04-20T16:39:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1R72LzcpgpmAQ/+JGblJqHbFsjhQrkIsov4k7PHHep2T8q3w1pAvy3XocJS
            3DUocEDiYZ+I1X5/s0VW6eyZ4JPXhk56j7QA0QeSD4gYmK9/DTFS7pWGgZKdfDzP
            51eq7AR5sQmHNAbt+GtFlspX885M+Y9tuV7PgXuXRUjD1IN8JLnqZaRspOweiyJk
            63RWThX1Eyygctdcz2CuI8dfBXXrlr9xT8XwG3o2MyKcvhI/xpiaYA/gdXp5C0RP
            pmKN6ZrYltBkR+8k6PDdJT97ZGTNCxS2bxAx6euOGzaygkMZCE76+0c5osqLYwID
            kjDCJya0fvbnt2Pa8UnEnT5s0cr6v5EnkXudo1A7HQmZ8p2cn3Wc64Zg4wIvpnB1
            IOYI8piAS/x9nAIU+orwlroDqK3+LZMOeakdcgzMel+peEZ6B7xA79FLA8sHTlBr
            khbjS6yvlJBEyj7r8GjCTXhjzuSLBaNya+m5RQlkXuUPEqb+jQVG0pv729nqUk1T
            z+9/y0YFkgwzLzHvwCzkrmt8IfPsoVpygThraPlEpGiTKpsIGHBFrOAzWBorI+aa
            brkMFPgQWLD2OHwmV65krkyvRPoI0XOMjk79fvD97RzNTD2o/Y0E6sZBZISyP0bh
            w9es0IjkzbU+alSDhwEpJKL3AKGR2r1DtJpVVDxrwO/rZ0Noz01qcJrDpqXn2CnS
            XAFnN+kRpzWeyPWP18bUCBAF0y3DAdl9DywuofCoqT/gkVt3hj2axdvLXafShMnn
            u+ON3tYDFXsgt/JPgoaSFIvz+TkDLSXDtkP/fJobLHnfNEKAFauVn9IqPOeK
            =0R7Y
            -----END PGP MESSAGE-----
          fp: 08083A92DBB719D2E10998259B44720A645D6802
    encrypted_regex: ^(data|stringData|email|apiToken)$
    version: 3.12.2
