apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    apiToken: ENC[AES256_GCM,data:LFRofPRexB+LeLs6X3W67eIid1THqR5O6oLz54YvJ5OVCCz7E8LlCQ==,iv:x/8fjmQ8At54riCG+wMSkWZdmEy88+DClQ7C9tnvpBg=,tag:vv8WK2ogztXHeoS0+2h12w==,type:str]
sops:
    lastmodified: "2026-04-20T16:33:14Z"
    mac: ENC[AES256_GCM,data:yP9ooMdVPTo4J4mprrDJUiDvV1NkRKfXM0VJJsZflJXpk/zO6iezJbWplqy2s5IbXvhG0B9PDk+Tjva+mtqQ/BjQJb3dsG7TS0mY/YIfx5J7Eeq/xuBKHd+ySiojWD9LsuQZXTQH60+xoGCqFUUeIU0Ph6QRPes1S8ZsOOa7qpg=,iv:fHtwPoLGv6oPHBMzXksGPjHyS74Z9Yq86HJa/+pTwhI=,tag:dOhZGmOiRm4OqhW8YxgnSg==,type:str]
    pgp:
        - created_at: "2026-04-20T16:33:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1R72LzcpgpmAQ/+J4bB2ABlCu/UdrgraPuE+KcSeyNOSTfT60TtNTpYYOKt
            jkLPAENBjy5maqZFNiYB+DVFyZUfUlyUEcG/ixWwaCzDLafQH/wMUmXKrL4+7MEB
            XUxYcX6adG/oDXxIBmEM/RFY3ZLcuDzg5e+dKEsSCw+quLDMjz9E2S8yo6hE63G/
            kVPcvkTnO/Q7FwteFhKEbWKaQ91lWOyMkWejbsIV0ND+p8QUWzW9PpHdkdArZQrV
            Y3tu70Gm1BPHwXxYnTi9qPEJH/5dcvu7dR4hblaTTcKqc29bY347W2aWbDJBJM4O
            NRd53ywLDyH+V7EdCmnn7KNT3/cOfN5gb3Sw64WHNPbiobwnIVjvN8Iz4+loPVmW
            SEAJjH7z5lR0Wy3q55dRZBy44uvfpYSeG5tJD8Iq8Vu84FeZ+dSmP/kBsmYYq7tM
            RWWkQ0QhDIJMMxcgJybNApBLKwHnl9E0Lfc4RXc4715canA2JhQBAnPK5jX4+ogJ
            4lf8ZHcqgZbcXGzMCDB3s9wZYp84uGNF8LhjcSjkJzsuM3iHvAbu2DkmX4vF/EL+
            mc4+WqqCn9uDkr0iLuqdPEpaNuSliIZTTqLHORUfjklyrjS5sXVV3xTEM93D/8ts
            zVluEHrn7oL787Kt+ZFxudKysKbrlt0ikSfZUHZCvzlrbCeW7uCTI7+dyqk5TbHS
            XgEaOB4laB1pDRua8RY2sG/DRLWLyP1xaPEw+/sgRCyo58Oir1WcPyCDFeHVxbUE
            LC/NCuGjI+ocV1ZckmgPimgxBBAA0bkL/TpZLRCxj3uZB4T700u5JAjJMOYQi+Y=
            =T/Zc
            -----END PGP MESSAGE-----
          fp: 08083A92DBB719D2E10998259B44720A645D6802
    encrypted_regex: ^(data|stringData|email|apiToken)$
    version: 3.12.2
