apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secret
    namespace: open-webui
type: Opaque
stringData:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:pQCnrBDyeVn5k2wPYSLPl2xWvcbp7LPUS9XMlS6YOj37K1JsDJOFWrhjlWPqXzDbg0OKNmKFsd7O90uFD+oQDQ==,iv:DP4DybklqAZinZ2cIOJtvWQ3ZLig+PgPVGaf8eX7yqA=,tag:uFDFOYXiRDApt31i/G7HRg==,type:str]
sops:
    lastmodified: "2026-05-19T19:54:12Z"
    mac: ENC[AES256_GCM,data:bUE8toDalPS5wpMoBnSKj/HFZPrBOt7KlCBvCHpZrrKNzxJpvLtPnfN5YnsHzyfapa3mmIbKjO+TvDVfTjalR+pDFvmpTqkpmEpiSMNeqRmxVaYc3B7G+stZc6MLYZJrnaI+MFgJfI1dE/+nIlDD1/KEVDR35vipxKGsB3RjFog=,iv:6iU1ugTZezSnnjU6O+zvP+TCvgQbxPBrm4SsmjfDLnw=,tag:ADnR4hdJo6AFhANVBAw6RA==,type:str]
    pgp:
        - created_at: "2026-05-19T19:54:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1R72LzcpgpmARAAmjMG90gOhEs7Qe2571qlYHPEsp6a3ehGSRJ3Tcqlno7D
            JMUyTQoNMK7EcQz4rORmG4KvppJXbZZ5fpAeEl0WP00ArbEYwkLkIs0MX6/HU50x
            L67ccBKiwLjyHaNa4OX6P8o8uSlolPSltCBR5K7Qba9Sr1dfR/k5mnZjWfxAhB5n
            nhN94C73fIRTgX+Wg0Z6Bg98ySfjmJP2FGGDYF80HKOPy8GWUhbNzVO7AmnKfH2x
            MzkP7w3zPTxxsmty2iJUFnffKJYoRSsVWuvqTiiU271K2cWcSmc/Ks0VPzvUNQA3
            6ZJj99uUjB9aaAyFVorbvj6QpCnrMW01DhErJvxFC7OFAxNgYghtoIW2yWPZd7pG
            x91uinzFnkFE/oyarbO61+4pcVhAw2Ps/DExht6AnnWA8Zog8LhKhNwTFRm8l00l
            a+ekok+SJy2wbBcwWUe3TIo7ifbHvbCxw2+/lv3QynRo4RA6ZpcwiqbdPo/uBjwE
            cXZ5Nzf0rxn4j+kpnOGFlhbh4wd6UYHLjdEr7sRZv2y50faOe1AMBcohNxK9IZri
            HxHRXsYBsT8e6Rqmhf9YIJF6oix8lYiUfi1hSaKGwtQKG76eM+FEXHkPV5cr7D83
            5NjSWxHDKD500qiIMXcbVUyw0afnk3UqcRFcMoVA55txx770uV8mh8kP0avBlr/S
            XgECitO3dAlpQJqhtwN/m6vmOMzXAYrGLWAm13v0TTL6c8T9HRISWkfKMxfgg146
            l1D+LdSzz2EBIzOiMhHFg3GoXiaKBMDRprcYQB3/0gEv9sISPHqkEIoyeNcKLXw=
            =opQm
            -----END PGP MESSAGE-----
          fp: 08083A92DBB719D2E10998259B44720A645D6802
    encrypted_regex: ^(data|stringData|email|apiToken|host|hosts)$
    version: 3.12.2
