apiVersion: v1
kind: Service
metadata:
  name: minecraft-svc-lb
  namespace: minecraft
spec:
  selector:
    app: minecraft
  ports:
    - name: minecraft
      protocol: TCP
      port: 25565
      targetPort: minecraft
  type: LoadBalancer
